import Homepage from 'components/Homepage'
import Head from 'next/head'

export default function Index() {
  return (
    <>
      <Head>
        <title>Apeswap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="preload"
        />
      </Head>
      <Homepage />
    </>
  )
}
