import { useWeb3React } from '@web3-react/core'
import Head from 'next/head'
import Home from './home'

export default function Index() {
  return (
    <>
      <Head>
        <title>Apeswap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
