import { useWeb3React } from "@web3-react/core";
import Homepage from "components/Homepage";
import { Flex } from "components/uikit";
import Head from "next/head";
import Script from "next/script";
import Home from "./home";

export default function Index() {
  return (
    <>
      <Head>
        <title>Apeswap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="/theme.js" strategy='beforeInteractive' />
      </Head>
      <Homepage />
    </>
  );
}
