export const QUERY_KEYS = {
  INDUSTRY_STATS: 'industryStats',
  HISTORICAL_INDUSTRY_STATS: 'historicalIndustryStats',
  LHD_PROFILES: 'lhdProfiles',
  LHD_PROFILE: 'lhdProfile',
  LHD_PASSWORD_VERIFIED: 'lhdPasswordVerified',
  HOMEPAGE_STATS: 'homepageStats',
  LIVE_AND_UPCOMING: 'liveAndUpcoming',
  TVL_STATS: 'tvlStats',
  WIDO_QUOTE: 'widoQuote',
  WIDO_ALLOWANCE: 'widoAllowance',
  WIDO_APPROVAL: 'widoApproval',
  WIDO_SIGN_APPROVAL: 'widoSignApproval',
  TOKEN_HISTORIC: 'tokenHistoric',
  BONDS_LANDING: 'bondsLanding',
}
